### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by Beijia11** [fudan-generative-vision/champ#12]
Hi :) Champ is really an inspiring work! During my experiment, Champ shows a high demand of memory and I cannot run the inference code on 3090 due to out of memory. May I ask is there any solution to solve this except changing to A10

**Comment by ShenhaoZhu** [comment]
Hi, thank you for your attention. You can edit `inference,yaml` and switch to other example data with less frames to reduce VRAM usage. I have already tested motion-02 on an RTX 3090, and it works :).
